spring:
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    type: mocked

server:
  error:
    include-message: always

service:
  coingecko:
    base-url: https://yakman.free.beeceptor.com/
    pages: 1
